# MinIO 跨网段部署示例配置
# 适用于节点分布在不同网段的场景
#
# 示例网络拓扑：
# - 节点1: 192.168.1.10  (办公网络)
# - 节点2: 10.0.0.20     (数据中心A)
# - 节点3: 172.16.0.30   (数据中心B)
# - 节点4: 203.0.113.40  (云服务器)

version: "3.8"

services:
  minio:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/minio/minio:RELEASE.2025-01-20T14-49-07Z
    hostname: minio-node2 # 每个节点修改为对应名称

    volumes:
      - /data1:/data1
      - /data2:/data2

    # 使用host网络模式，直接使用主机网络
    # 适用于跨网段部署，避免Docker网络转发的复杂性
    network_mode: host

    # host模式下不需要端口映射，容器直接使用主机端口
    # ports:
    #   - "9000:9000"
    #   - "9001:9001"

    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      # 如果使用HTTPS，添加以下环境变量
      # MINIO_SERVER_URL: https://your-domain.com:9000
      # MINIO_BROWSER_REDIRECT_URL: https://your-domain.com:9001

    # 跨网段部署必须完整列出所有节点地址
    # 不能使用 {10...13} 的简化语法
    command: >
      server --console-address ":9001"
      http://172.24.168.85:9000/data1
      http://172.24.168.85:9000/data2
      http://172.24.170.19:9000/data1
      http://172.24.170.19:9000/data2

volumes:
  data1:
    driver: local
  data2:
    driver: local
# 部署前检查清单：
# 1. 网络连通性测试：
#    telnet 192.168.1.10 9000
#    telnet 10.0.0.20 9000
#    telnet 172.16.0.30 9000
#    telnet 203.0.113.40 9000
#
# 2. 防火墙配置：
#    sudo ufw allow 9000/tcp
#    sudo ufw allow 9001/tcp
#
# 3. 时间同步：
#    sudo ntpdate -s time.nist.gov
#
# 4. 数据目录权限：
#    sudo mkdir -p /data1 /data2
#    sudo chown -R 1000:1000 /data1 /data2
