# MinIO 多节点分布式部署配置
#
# 部署架构：
# - 每台物理机运行一个MinIO容器实例
# - 需要4台独立的服务器组成集群
# - 通过真实IP地址进行节点间通信
# - 支持跨网段部署
#
# 服务器IP规划示例：
# 场景1 - 同网段部署：
# - 节点1: 192.168.1.10
# - 节点2: 192.168.1.11
# - 节点3: 192.168.1.12
# - 节点4: 192.168.1.13
#
# 场景2 - 跨网段部署：
# - 节点1: 192.168.1.10  (内网)
# - 节点2: 10.0.0.20     (内网)
# - 节点3: 172.16.0.30   (内网)
# - 节点4: 203.0.113.40  (公网)
#
# 跨网段部署要求：
# 1. 所有节点之间必须能够直接通信（路由可达）
# 2. 防火墙/安全组开放9000和9001端口
# 3. 如果有NAT，需要配置端口转发
# 4. 公网节点建议配置SSL证书
#
# 部署步骤：
# 1. 在每台机器上创建数据目录: mkdir -p /data1 /data2
# 2. 修改每台机器的hostname配置
# 3. 确保所有机器网络互通，防火墙开放9000和9001端口
# 4. 根据实际IP地址修改command中的地址配置
# 5. 在所有机器上同时启动: docker-compose -f docker-compose-distributed.yml up -d

version: "3.8"

services:
  minio:
    # 使用华为云镜像源，国内访问更快
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/minio/minio:RELEASE.2025-01-18T00-31-37Z

    # 容器主机名，每个节点需要修改为不同的名称
    # 节点1: minio-node1, 节点2: minio-node2, 节点3: minio-node3, 节点4: minio-node4
    hostname: minio-node1

    # 数据卷挂载：将宿主机目录挂载到容器内
    # 每个节点提供2个数据端点，满足MinIO纠删码要求
    volumes:
      - /data1:/data1 # 第一个数据目录
      - /data2:/data2 # 第二个数据目录

    # 端口映射：所有节点使用相同端口（因为在不同物理机上）
    ports:
      - "9000:9000" # API服务端口
      - "9001:9001" # Web控制台端口

    # 环境变量：集群认证信息（所有节点必须相同）
    environment:
      MINIO_ROOT_USER: minioadmin # 管理员用户名
      MINIO_ROOT_PASSWORD: minioadmin # 管理员密码

    # 集群启动命令
    # --console-address ":9001": 指定控制台监听端口
    #
    # 同网段部署示例：
    # command: server --console-address ":9001" http://192.168.1.{10...13}:9000/data{1...2}
    #
    # 当前配置（请根据实际IP地址修改）：
    command: server --console-address ":9001" http://192.168.1.{10...13}:9000/data{1...2}

    # 加入自定义网络
    networks:
      - minio-network

# 网络配置
networks:
  minio-network:
    # 使用桥接网络驱动
    # 跨网段部署时，容器需要能够访问外部网络
    # 如果使用公网IP，建议使用host网络模式：
    # network_mode: host
    driver: bridge

# 数据卷配置
# 注意：这里定义的卷实际上不会被使用，因为我们直接挂载宿主机目录
# 但保留配置以确保兼容性
volumes:
  data1:
    driver: local # 本地存储驱动
  data2:
    driver: local # 本地存储驱动

# 集群特性说明：
# 1. 高可用性：4节点集群可以容忍最多1个节点故障
# 2. 纠删码：默认配置下，数据会被分片存储在8个端点上
# 3. 负载均衡：客户端可以连接任意节点进行读写操作
# 4. 数据一致性：所有节点共享相同的数据视图
#
# 访问地址：
# - API端点：http://192.168.1.10:9000 (或任意节点IP)
# - 控制台：http://192.168.1.10:9001 (或任意节点IP)
# - 用户名/密码：minioadmin/minioadmin
#
# 跨网段部署注意事项：
# 1. 网络连通性：
#    - 使用 telnet <IP> 9000 测试节点间连通性
#    - 确保路由表配置正确
#    - 如果有防火墙，需要开放9000和9001端口
#
# 2. 地址配置：
#    - 不能使用 {10...13} 的简化语法
#    - 必须完整列出所有节点的IP地址
#    - 示例：http://192.168.1.10:9000/data1 http://10.0.0.20:9000/data1 ...
#
# 3. DNS解析：
#    - 如果使用域名，确保所有节点都能解析
#    - 建议直接使用IP地址避免DNS问题
#
# 4. 云服务器部署：
#    - 注意内网IP和公网IP的区别
#    - 如果使用负载均衡，需要配置健康检查
#    - 安全组/防火墙规则要正确配置
#
# 通用注意事项：
# - 所有节点必须使用相同的MINIO_ROOT_USER和MINIO_ROOT_PASSWORD
# - 集群形成后，不能随意改变节点数量和地址配置
# - 建议配置NTP服务确保所有节点时间同步
# - 生产环境建议使用HTTPS和更强的密码
