version: "3.8"

services:
  minio1:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}

  minio2:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}

  minio3:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2
    ports:
      - "9020:9000"
      - "9021:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}

  minio4:
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/minio/minio:RELEASE.2025-06-13T11-33-47Z
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2
    ports:
      - "9030:9000"
      - "9031:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" http://minio{1...4}/data{1...2}

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
